export const SEARCH_USERS_AND_REPOS = 'SEARCH_USERS_AND_REPOS';
export const SET_LOADING = 'SET_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
