import axios from 'axios';

export const searchUsers = async query => {
  try {
    const res = await axios.get(
      `https://api.github.com/search/users?q=${query}`
    );
    console.log('res', res);
    console.log('res', JSON.stringify(res.data.items));
    return res.data.items;
  } catch (err) {
    console.log(err);
  }
};

const data = [
  {
    login: 'hel',
    id: 139333,
    node_id: 'MDQ6VXNlcjEzOTMzMw==',
    avatar_url: 'https://avatars0.githubusercontent.com/u/139333?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/hel',
    html_url: 'https://github.com/hel',
    followers_url: 'https://api.github.com/users/hel/followers',
    following_url: 'https://api.github.com/users/hel/following{/other_user}',
    gists_url: 'https://api.github.com/users/hel/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/hel/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/hel/subscriptions',
    organizations_url: 'https://api.github.com/users/hel/orgs',
    repos_url: 'https://api.github.com/users/hel/repos',
    events_url: 'https://api.github.com/users/hel/events{/privacy}',
    received_events_url: 'https://api.github.com/users/hel/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'HelKyle',
    id: 9882649,
    node_id: 'MDQ6VXNlcjk4ODI2NDk=',
    avatar_url: 'https://avatars2.githubusercontent.com/u/9882649?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/HelKyle',
    html_url: 'https://github.com/HelKyle',
    followers_url: 'https://api.github.com/users/HelKyle/followers',
    following_url:
      'https://api.github.com/users/HelKyle/following{/other_user}',
    gists_url: 'https://api.github.com/users/HelKyle/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/HelKyle/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/HelKyle/subscriptions',
    organizations_url: 'https://api.github.com/users/HelKyle/orgs',
    repos_url: 'https://api.github.com/users/HelKyle/repos',
    events_url: 'https://api.github.com/users/HelKyle/events{/privacy}',
    received_events_url: 'https://api.github.com/users/HelKyle/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'HelloZeroNet',
    id: 10350359,
    node_id: 'MDQ6VXNlcjEwMzUwMzU5',
    avatar_url: 'https://avatars0.githubusercontent.com/u/10350359?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/HelloZeroNet',
    html_url: 'https://github.com/HelloZeroNet',
    followers_url: 'https://api.github.com/users/HelloZeroNet/followers',
    following_url:
      'https://api.github.com/users/HelloZeroNet/following{/other_user}',
    gists_url: 'https://api.github.com/users/HelloZeroNet/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/HelloZeroNet/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/HelloZeroNet/subscriptions',
    organizations_url: 'https://api.github.com/users/HelloZeroNet/orgs',
    repos_url: 'https://api.github.com/users/HelloZeroNet/repos',
    events_url: 'https://api.github.com/users/HelloZeroNet/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/HelloZeroNet/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'lrhel',
    id: 20042211,
    node_id: 'MDQ6VXNlcjIwMDQyMjEx',
    avatar_url: 'https://avatars2.githubusercontent.com/u/20042211?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/lrhel',
    html_url: 'https://github.com/lrhel',
    followers_url: 'https://api.github.com/users/lrhel/followers',
    following_url: 'https://api.github.com/users/lrhel/following{/other_user}',
    gists_url: 'https://api.github.com/users/lrhel/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/lrhel/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/lrhel/subscriptions',
    organizations_url: 'https://api.github.com/users/lrhel/orgs',
    repos_url: 'https://api.github.com/users/lrhel/repos',
    events_url: 'https://api.github.com/users/lrhel/events{/privacy}',
    received_events_url: 'https://api.github.com/users/lrhel/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'hellerve',
    id: 7725188,
    node_id: 'MDQ6VXNlcjc3MjUxODg=',
    avatar_url: 'https://avatars3.githubusercontent.com/u/7725188?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/hellerve',
    html_url: 'https://github.com/hellerve',
    followers_url: 'https://api.github.com/users/hellerve/followers',
    following_url:
      'https://api.github.com/users/hellerve/following{/other_user}',
    gists_url: 'https://api.github.com/users/hellerve/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/hellerve/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/hellerve/subscriptions',
    organizations_url: 'https://api.github.com/users/hellerve/orgs',
    repos_url: 'https://api.github.com/users/hellerve/repos',
    events_url: 'https://api.github.com/users/hellerve/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/hellerve/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'helloqingfeng',
    id: 9712785,
    node_id: 'MDQ6VXNlcjk3MTI3ODU=',
    avatar_url: 'https://avatars2.githubusercontent.com/u/9712785?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/helloqingfeng',
    html_url: 'https://github.com/helloqingfeng',
    followers_url: 'https://api.github.com/users/helloqingfeng/followers',
    following_url:
      'https://api.github.com/users/helloqingfeng/following{/other_user}',
    gists_url: 'https://api.github.com/users/helloqingfeng/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/helloqingfeng/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/helloqingfeng/subscriptions',
    organizations_url: 'https://api.github.com/users/helloqingfeng/orgs',
    repos_url: 'https://api.github.com/users/helloqingfeng/repos',
    events_url: 'https://api.github.com/users/helloqingfeng/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/helloqingfeng/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'hellais',
    id: 424620,
    node_id: 'MDQ6VXNlcjQyNDYyMA==',
    avatar_url: 'https://avatars0.githubusercontent.com/u/424620?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/hellais',
    html_url: 'https://github.com/hellais',
    followers_url: 'https://api.github.com/users/hellais/followers',
    following_url:
      'https://api.github.com/users/hellais/following{/other_user}',
    gists_url: 'https://api.github.com/users/hellais/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/hellais/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/hellais/subscriptions',
    organizations_url: 'https://api.github.com/users/hellais/orgs',
    repos_url: 'https://api.github.com/users/hellais/repos',
    events_url: 'https://api.github.com/users/hellais/events{/privacy}',
    received_events_url: 'https://api.github.com/users/hellais/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'helloroman',
    id: 9623791,
    node_id: 'MDQ6VXNlcjk2MjM3OTE=',
    avatar_url: 'https://avatars2.githubusercontent.com/u/9623791?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/helloroman',
    html_url: 'https://github.com/helloroman',
    followers_url: 'https://api.github.com/users/helloroman/followers',
    following_url:
      'https://api.github.com/users/helloroman/following{/other_user}',
    gists_url: 'https://api.github.com/users/helloroman/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/helloroman/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/helloroman/subscriptions',
    organizations_url: 'https://api.github.com/users/helloroman/orgs',
    repos_url: 'https://api.github.com/users/helloroman/repos',
    events_url: 'https://api.github.com/users/helloroman/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/helloroman/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'hellock',
    id: 9102141,
    node_id: 'MDQ6VXNlcjkxMDIxNDE=',
    avatar_url: 'https://avatars3.githubusercontent.com/u/9102141?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/hellock',
    html_url: 'https://github.com/hellock',
    followers_url: 'https://api.github.com/users/hellock/followers',
    following_url:
      'https://api.github.com/users/hellock/following{/other_user}',
    gists_url: 'https://api.github.com/users/hellock/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/hellock/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/hellock/subscriptions',
    organizations_url: 'https://api.github.com/users/hellock/orgs',
    repos_url: 'https://api.github.com/users/hellock/repos',
    events_url: 'https://api.github.com/users/hellock/events{/privacy}',
    received_events_url: 'https://api.github.com/users/hellock/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'helen',
    id: 906334,
    node_id: 'MDQ6VXNlcjkwNjMzNA==',
    avatar_url: 'https://avatars1.githubusercontent.com/u/906334?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/helen',
    html_url: 'https://github.com/helen',
    followers_url: 'https://api.github.com/users/helen/followers',
    following_url: 'https://api.github.com/users/helen/following{/other_user}',
    gists_url: 'https://api.github.com/users/helen/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/helen/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/helen/subscriptions',
    organizations_url: 'https://api.github.com/users/helen/orgs',
    repos_url: 'https://api.github.com/users/helen/repos',
    events_url: 'https://api.github.com/users/helen/events{/privacy}',
    received_events_url: 'https://api.github.com/users/helen/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'heloameneses',
    id: 13964550,
    node_id: 'MDQ6VXNlcjEzOTY0NTUw',
    avatar_url: 'https://avatars0.githubusercontent.com/u/13964550?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/heloameneses',
    html_url: 'https://github.com/heloameneses',
    followers_url: 'https://api.github.com/users/heloameneses/followers',
    following_url:
      'https://api.github.com/users/heloameneses/following{/other_user}',
    gists_url: 'https://api.github.com/users/heloameneses/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/heloameneses/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/heloameneses/subscriptions',
    organizations_url: 'https://api.github.com/users/heloameneses/orgs',
    repos_url: 'https://api.github.com/users/heloameneses/repos',
    events_url: 'https://api.github.com/users/heloameneses/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/heloameneses/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'helena',
    id: 406103,
    node_id: 'MDQ6VXNlcjQwNjEwMw==',
    avatar_url: 'https://avatars2.githubusercontent.com/u/406103?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/helena',
    html_url: 'https://github.com/helena',
    followers_url: 'https://api.github.com/users/helena/followers',
    following_url: 'https://api.github.com/users/helena/following{/other_user}',
    gists_url: 'https://api.github.com/users/helena/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/helena/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/helena/subscriptions',
    organizations_url: 'https://api.github.com/users/helena/orgs',
    repos_url: 'https://api.github.com/users/helena/repos',
    events_url: 'https://api.github.com/users/helena/events{/privacy}',
    received_events_url: 'https://api.github.com/users/helena/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'helfer',
    id: 6569980,
    node_id: 'MDQ6VXNlcjY1Njk5ODA=',
    avatar_url: 'https://avatars3.githubusercontent.com/u/6569980?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/helfer',
    html_url: 'https://github.com/helfer',
    followers_url: 'https://api.github.com/users/helfer/followers',
    following_url: 'https://api.github.com/users/helfer/following{/other_user}',
    gists_url: 'https://api.github.com/users/helfer/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/helfer/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/helfer/subscriptions',
    organizations_url: 'https://api.github.com/users/helfer/orgs',
    repos_url: 'https://api.github.com/users/helfer/repos',
    events_url: 'https://api.github.com/users/helfer/events{/privacy}',
    received_events_url: 'https://api.github.com/users/helfer/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'hellyeah',
    id: 1475361,
    node_id: 'MDQ6VXNlcjE0NzUzNjE=',
    avatar_url: 'https://avatars0.githubusercontent.com/u/1475361?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/hellyeah',
    html_url: 'https://github.com/hellyeah',
    followers_url: 'https://api.github.com/users/hellyeah/followers',
    following_url:
      'https://api.github.com/users/hellyeah/following{/other_user}',
    gists_url: 'https://api.github.com/users/hellyeah/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/hellyeah/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/hellyeah/subscriptions',
    organizations_url: 'https://api.github.com/users/hellyeah/orgs',
    repos_url: 'https://api.github.com/users/hellyeah/repos',
    events_url: 'https://api.github.com/users/hellyeah/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/hellyeah/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'Nirgalz',
    id: 3767939,
    node_id: 'MDQ6VXNlcjM3Njc5Mzk=',
    avatar_url: 'https://avatars0.githubusercontent.com/u/3767939?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Nirgalz',
    html_url: 'https://github.com/Nirgalz',
    followers_url: 'https://api.github.com/users/Nirgalz/followers',
    following_url:
      'https://api.github.com/users/Nirgalz/following{/other_user}',
    gists_url: 'https://api.github.com/users/Nirgalz/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Nirgalz/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Nirgalz/subscriptions',
    organizations_url: 'https://api.github.com/users/Nirgalz/orgs',
    repos_url: 'https://api.github.com/users/Nirgalz/repos',
    events_url: 'https://api.github.com/users/Nirgalz/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Nirgalz/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'Helios-Protocol',
    id: 39318468,
    node_id: 'MDQ6VXNlcjM5MzE4NDY4',
    avatar_url: 'https://avatars3.githubusercontent.com/u/39318468?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Helios-Protocol',
    html_url: 'https://github.com/Helios-Protocol',
    followers_url: 'https://api.github.com/users/Helios-Protocol/followers',
    following_url:
      'https://api.github.com/users/Helios-Protocol/following{/other_user}',
    gists_url: 'https://api.github.com/users/Helios-Protocol/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Helios-Protocol/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/Helios-Protocol/subscriptions',
    organizations_url: 'https://api.github.com/users/Helios-Protocol/orgs',
    repos_url: 'https://api.github.com/users/Helios-Protocol/repos',
    events_url: 'https://api.github.com/users/Helios-Protocol/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Helios-Protocol/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'helei112g',
    id: 10877127,
    node_id: 'MDQ6VXNlcjEwODc3MTI3',
    avatar_url: 'https://avatars0.githubusercontent.com/u/10877127?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/helei112g',
    html_url: 'https://github.com/helei112g',
    followers_url: 'https://api.github.com/users/helei112g/followers',
    following_url:
      'https://api.github.com/users/helei112g/following{/other_user}',
    gists_url: 'https://api.github.com/users/helei112g/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/helei112g/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/helei112g/subscriptions',
    organizations_url: 'https://api.github.com/users/helei112g/orgs',
    repos_url: 'https://api.github.com/users/helei112g/repos',
    events_url: 'https://api.github.com/users/helei112g/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/helei112g/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'hellosean1025',
    id: 17695103,
    node_id: 'MDQ6VXNlcjE3Njk1MTAz',
    avatar_url: 'https://avatars0.githubusercontent.com/u/17695103?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/hellosean1025',
    html_url: 'https://github.com/hellosean1025',
    followers_url: 'https://api.github.com/users/hellosean1025/followers',
    following_url:
      'https://api.github.com/users/hellosean1025/following{/other_user}',
    gists_url: 'https://api.github.com/users/hellosean1025/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/hellosean1025/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/hellosean1025/subscriptions',
    organizations_url: 'https://api.github.com/users/hellosean1025/orgs',
    repos_url: 'https://api.github.com/users/hellosean1025/repos',
    events_url: 'https://api.github.com/users/hellosean1025/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/hellosean1025/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'helaili',
    id: 2787414,
    node_id: 'MDQ6VXNlcjI3ODc0MTQ=',
    avatar_url: 'https://avatars0.githubusercontent.com/u/2787414?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/helaili',
    html_url: 'https://github.com/helaili',
    followers_url: 'https://api.github.com/users/helaili/followers',
    following_url:
      'https://api.github.com/users/helaili/following{/other_user}',
    gists_url: 'https://api.github.com/users/helaili/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/helaili/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/helaili/subscriptions',
    organizations_url: 'https://api.github.com/users/helaili/orgs',
    repos_url: 'https://api.github.com/users/helaili/repos',
    events_url: 'https://api.github.com/users/helaili/events{/privacy}',
    received_events_url: 'https://api.github.com/users/helaili/received_events',
    type: 'User',
    site_admin: true,
    score: 1
  },
  {
    login: 'heldr',
    id: 134727,
    node_id: 'MDQ6VXNlcjEzNDcyNw==',
    avatar_url: 'https://avatars3.githubusercontent.com/u/134727?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/heldr',
    html_url: 'https://github.com/heldr',
    followers_url: 'https://api.github.com/users/heldr/followers',
    following_url: 'https://api.github.com/users/heldr/following{/other_user}',
    gists_url: 'https://api.github.com/users/heldr/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/heldr/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/heldr/subscriptions',
    organizations_url: 'https://api.github.com/users/heldr/orgs',
    repos_url: 'https://api.github.com/users/heldr/repos',
    events_url: 'https://api.github.com/users/heldr/events{/privacy}',
    received_events_url: 'https://api.github.com/users/heldr/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'helghareeb',
    id: 1383487,
    node_id: 'MDQ6VXNlcjEzODM0ODc=',
    avatar_url: 'https://avatars1.githubusercontent.com/u/1383487?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/helghareeb',
    html_url: 'https://github.com/helghareeb',
    followers_url: 'https://api.github.com/users/helghareeb/followers',
    following_url:
      'https://api.github.com/users/helghareeb/following{/other_user}',
    gists_url: 'https://api.github.com/users/helghareeb/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/helghareeb/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/helghareeb/subscriptions',
    organizations_url: 'https://api.github.com/users/helghareeb/orgs',
    repos_url: 'https://api.github.com/users/helghareeb/repos',
    events_url: 'https://api.github.com/users/helghareeb/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/helghareeb/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'helloyou2012',
    id: 1798364,
    node_id: 'MDQ6VXNlcjE3OTgzNjQ=',
    avatar_url: 'https://avatars0.githubusercontent.com/u/1798364?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/helloyou2012',
    html_url: 'https://github.com/helloyou2012',
    followers_url: 'https://api.github.com/users/helloyou2012/followers',
    following_url:
      'https://api.github.com/users/helloyou2012/following{/other_user}',
    gists_url: 'https://api.github.com/users/helloyou2012/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/helloyou2012/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/helloyou2012/subscriptions',
    organizations_url: 'https://api.github.com/users/helloyou2012/orgs',
    repos_url: 'https://api.github.com/users/helloyou2012/repos',
    events_url: 'https://api.github.com/users/helloyou2012/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/helloyou2012/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'HelloWorld017',
    id: 3919433,
    node_id: 'MDQ6VXNlcjM5MTk0MzM=',
    avatar_url: 'https://avatars1.githubusercontent.com/u/3919433?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/HelloWorld017',
    html_url: 'https://github.com/HelloWorld017',
    followers_url: 'https://api.github.com/users/HelloWorld017/followers',
    following_url:
      'https://api.github.com/users/HelloWorld017/following{/other_user}',
    gists_url: 'https://api.github.com/users/HelloWorld017/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/HelloWorld017/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/HelloWorld017/subscriptions',
    organizations_url: 'https://api.github.com/users/HelloWorld017/orgs',
    repos_url: 'https://api.github.com/users/HelloWorld017/repos',
    events_url: 'https://api.github.com/users/HelloWorld017/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/HelloWorld017/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'hellman',
    id: 571028,
    node_id: 'MDQ6VXNlcjU3MTAyOA==',
    avatar_url: 'https://avatars2.githubusercontent.com/u/571028?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/hellman',
    html_url: 'https://github.com/hellman',
    followers_url: 'https://api.github.com/users/hellman/followers',
    following_url:
      'https://api.github.com/users/hellman/following{/other_user}',
    gists_url: 'https://api.github.com/users/hellman/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/hellman/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/hellman/subscriptions',
    organizations_url: 'https://api.github.com/users/hellman/orgs',
    repos_url: 'https://api.github.com/users/hellman/repos',
    events_url: 'https://api.github.com/users/hellman/events{/privacy}',
    received_events_url: 'https://api.github.com/users/hellman/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'helios66',
    id: 678974,
    node_id: 'MDQ6VXNlcjY3ODk3NA==',
    avatar_url: 'https://avatars3.githubusercontent.com/u/678974?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/helios66',
    html_url: 'https://github.com/helios66',
    followers_url: 'https://api.github.com/users/helios66/followers',
    following_url:
      'https://api.github.com/users/helios66/following{/other_user}',
    gists_url: 'https://api.github.com/users/helios66/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/helios66/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/helios66/subscriptions',
    organizations_url: 'https://api.github.com/users/helios66/orgs',
    repos_url: 'https://api.github.com/users/helios66/repos',
    events_url: 'https://api.github.com/users/helios66/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/helios66/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'hellofromtonya',
    id: 7284611,
    node_id: 'MDQ6VXNlcjcyODQ2MTE=',
    avatar_url: 'https://avatars0.githubusercontent.com/u/7284611?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/hellofromtonya',
    html_url: 'https://github.com/hellofromtonya',
    followers_url: 'https://api.github.com/users/hellofromtonya/followers',
    following_url:
      'https://api.github.com/users/hellofromtonya/following{/other_user}',
    gists_url: 'https://api.github.com/users/hellofromtonya/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/hellofromtonya/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/hellofromtonya/subscriptions',
    organizations_url: 'https://api.github.com/users/hellofromtonya/orgs',
    repos_url: 'https://api.github.com/users/hellofromtonya/repos',
    events_url: 'https://api.github.com/users/hellofromtonya/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/hellofromtonya/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'helhum',
    id: 904370,
    node_id: 'MDQ6VXNlcjkwNDM3MA==',
    avatar_url: 'https://avatars2.githubusercontent.com/u/904370?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/helhum',
    html_url: 'https://github.com/helhum',
    followers_url: 'https://api.github.com/users/helhum/followers',
    following_url: 'https://api.github.com/users/helhum/following{/other_user}',
    gists_url: 'https://api.github.com/users/helhum/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/helhum/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/helhum/subscriptions',
    organizations_url: 'https://api.github.com/users/helhum/orgs',
    repos_url: 'https://api.github.com/users/helhum/repos',
    events_url: 'https://api.github.com/users/helhum/events{/privacy}',
    received_events_url: 'https://api.github.com/users/helhum/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'hellobrian',
    id: 4185382,
    node_id: 'MDQ6VXNlcjQxODUzODI=',
    avatar_url: 'https://avatars3.githubusercontent.com/u/4185382?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/hellobrian',
    html_url: 'https://github.com/hellobrian',
    followers_url: 'https://api.github.com/users/hellobrian/followers',
    following_url:
      'https://api.github.com/users/hellobrian/following{/other_user}',
    gists_url: 'https://api.github.com/users/hellobrian/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/hellobrian/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/hellobrian/subscriptions',
    organizations_url: 'https://api.github.com/users/hellobrian/orgs',
    repos_url: 'https://api.github.com/users/hellobrian/repos',
    events_url: 'https://api.github.com/users/hellobrian/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/hellobrian/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'helloxz',
    id: 7276531,
    node_id: 'MDQ6VXNlcjcyNzY1MzE=',
    avatar_url: 'https://avatars2.githubusercontent.com/u/7276531?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/helloxz',
    html_url: 'https://github.com/helloxz',
    followers_url: 'https://api.github.com/users/helloxz/followers',
    following_url:
      'https://api.github.com/users/helloxz/following{/other_user}',
    gists_url: 'https://api.github.com/users/helloxz/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/helloxz/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/helloxz/subscriptions',
    organizations_url: 'https://api.github.com/users/helloxz/orgs',
    repos_url: 'https://api.github.com/users/helloxz/repos',
    events_url: 'https://api.github.com/users/helloxz/events{/privacy}',
    received_events_url: 'https://api.github.com/users/helloxz/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  },
  {
    login: 'Hellcatzm',
    id: 19740222,
    node_id: 'MDQ6VXNlcjE5NzQwMjIy',
    avatar_url: 'https://avatars1.githubusercontent.com/u/19740222?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Hellcatzm',
    html_url: 'https://github.com/Hellcatzm',
    followers_url: 'https://api.github.com/users/Hellcatzm/followers',
    following_url:
      'https://api.github.com/users/Hellcatzm/following{/other_user}',
    gists_url: 'https://api.github.com/users/Hellcatzm/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Hellcatzm/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Hellcatzm/subscriptions',
    organizations_url: 'https://api.github.com/users/Hellcatzm/orgs',
    repos_url: 'https://api.github.com/users/Hellcatzm/repos',
    events_url: 'https://api.github.com/users/Hellcatzm/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Hellcatzm/received_events',
    type: 'User',
    site_admin: false,
    score: 1
  }
];
